:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 10
  :pidfile: /var/www/panda_coins/shared/tmp/pids/sidekiq.pid
  :logfile: /var/www/panda_coins/current/log/sidekiq_production.log
:queues:
  - critical
  - high
  - default
  - low
